services:
  movie-analyst-api:
    build:
      context: ./movie-analyst-api
      dockerfile: Dockerfile
    container_name: movie-analyst-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=dev
      - DB_HOST=moviedb
      - DB_PASS=root_password
      - DB_USER=root
      - PORT=3000
    depends_on:
      - moviedb
    networks:
      - backend
    restart: unless-stopped

  movie-analyst-ui:
    build:
      context: ./movie-analyst-ui
      dockerfile: Dockerfile
    container_name: movie-analyst-ui
    ports:
      - "3030:3030"
    environment:
      - PORT=3030
      - BACKEND_URL="movie-analyst-api:3000"
    depends_on:
      - movie-analyst-api
    networks:
      - backend
    restart: unless-stopped

  moviedb:
    image: mariadb:10.6.17
    container_name: moviedb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root_password
      MARIADB_DATABASE: movie_db

    ports:
      - "3306:3306"
    networks:
      - backend

networks:
  backend:
    driver: bridge
