services:
  movie-analyst-api:
    build:
      context: ./movie-analyst-api
      dockerfile: Dockerfile
    container_name: movie-analyst-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=dev
      - DB_HOST=moviedb
      - DB_PASS=root_password
      - DB_USER=root
      - PORT=3000
    depends_on:
      - mysql
    networks:
      - backend
    restart: unless-stopped

  movie-analyst-ui:
    build:
      context: ./movie-analyst-ui
      dockerfile: Dockerfile
    container_name: movie-analyst-ui
    ports:
      - "3030:3030"
    environment:
      - PORT=3030
      - BACKEND_URL="movie-analyst-api:3000"
    depends_on:
      - movie-analyst-api
    networks:
      - backend
    restart: unless-stopped

  mysql:
    image: mysql:5.7.44
    container_name: moviedb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: movie_analyst_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
    ports:
      - "3306:3306"
    networks:
      - backend

networks:
  backend:
    driver: bridge
