---
apiVersion: v1
kind: Service
metadata:
  name: movie-analyst-ui
  labels:
    name: movie-analyst-ui
spec:
  ports:
      - port: 80
  type: NodePort
  selector:
    app: movie-analyst-ui
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: movie-analyst-ui
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          service:
            name: movie-analyst-ui
            port: 
              number: 80