apiVersion: v1
kind: Service
metadata:
  name: movie-analyst-ui
  labels:
    name: movie-analyst-ui
spec:
  ports:
    - port: 80
      name: web
  type: NodePort
  selector:
    app: movie-analyst-ui