apiVersion: v1
kind: Service
metadata:
  name: movie-analyst-ui
  labels:
    name: movie-analyst-ui
spec:
  ports:
    - name: web
      port: 80
  type: "LoadBalancer"
  selector:
    app: movie-analyst-ui