apiVersion: v1
kind: Service
metadata:
  name: movie-analyst-ui
  labels:
    name: movie-analyst-ui
spec:
  ports:
    - name: Website
      protocol: TCP
      port: 80
      targetPort: 80
  type: "ClusterIP"
  selector:
    app: movie-analyst-ui