---
apiVersion: v1
kind: Service
metadata:
  name: sshd-jumpserver
  labels:
    name: sshd-jumpserver
spec:
  ports:
    - name: ssh
      port: 22
  type: "NodePort"
  selector:
    app: sshd-jumpserver
---
apiVersion: v1
kind: Service
metadata:
  name: sshd-jumpserver
  labels:
    name: sshd-jumpserver
spec:
  ports:
  - port: 22
    protocol: TCP
    targetPort: 2200
  selector:
    app: sshd-jumpserver
  type: LoadBalancer