- name: Install k3s
  hosts: localhost
  roles:
   - role: k8s
  tasks:
   - name: Create pub keys folder
     become: true
     ansible.builtin.file:
      path: /root/pubkeys
      state: directory
      mode: '0755'

   - name: Apply kubernetes manifests
     tags: manifests
     block:
      - name: Find Kubernetes manifests
        ansible.builtin.find:
         paths: "/root/devops-rampup/infrastructure/kubernetes"
         patterns: "*.yaml"
         recurse: true
        register: k8s_files

      - name: Apply manifests
        kubernetes.core.k8s:
         state: present
         src: "{{ item.path }}"
        loop: "{{ k8s_files.files }}"
