- name: Install k3s
  hosts: localhost
  roles:
   - role: k8s
  tasks:
   - name: Create pub keys folder
     become: true
     ansible.builtin.file:
      path: /root/pubkeys
      state: directory
      mode: '0755'
   - name: Apply kubernetes manifests
     tags: manifests
     kubernetes.core.k8s:
      state: present
      definition: "{{ lookup('template', '{{ item }}') }}"
      namespace: default
     with_fileglob:
      - "/root/devops-rampup/infrastructure/kubernetes/**/*.yaml"
