- name: Install k3s
  hosts: localhost
  roles:
   - role: k8s
  tasks:
   - name: Create pub keys folder
     become: true
     ansible.builtin.file:
      path: /root/pubkeys
      state: directory
      mode: '0755'
   - name: Apply kubernetes manifests
     tags: manifests
     ansible.builtin.command:
      cmd: "kubectl apply -R -f ."
      chdir: "/root/devops-rampup/infrastructure/kubernetes/"
     changed_when: true
