- name: Install k3s
  hosts: localhost
  roles:
   - role: k8s
  tasks:
   - name: Create pub keys folder
     become: true
     ansible.builtin.file:
      path: /root/pubkeys
      state: directory
      mode: '0755'

   - name: Apply kubernetes manifests
     tags: manifests
     become: true
     block:
      - name: Install python kubernetes
        ansible.builtin.package:
         name: python3-kubernetes
         state: present

      - name: Install kube config for ansible module
        ansible.builtin.command: |
         "k3s kubectl config view --flatten > /root/.kube/config"
        args:
         creates: /root/.kube/config

      - name: Find Kubernetes manifests
        ansible.builtin.find:
         paths: "/root/devops-rampup/infrastructure/kubernetes"
         patterns: "*.yaml"
         recurse: true
        register: k8s_files

      - name: Apply manifests
        kubernetes.core.k8s:
         state: present
         src: "{{ item.path }}"
        loop: "{{ k8s_files.files }}"
