- name: Configure RDS Credentials
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Install MariaDB Client
      ansible.builtin.package:
        name: mariadb-client
        state: present

    - name: Generate Random Password
      ansible.builtin.command: echo "{{ lookup('password', '/dev/null length=20 chars=ascii_letters,digits') }}"
      register: generated_password
      changed_when: true

    - name: Connect to RDS and Change Password
      ansible.builtin.command: |
        mysql -h "{{ RDS_ENDPOINT.split(':')[0] }}" -u admin -p"tmp_pass" -e "ALTER USER 'admin'@'%' IDENTIFIED BY '{{ generated_password.stdout }}';"
      changed_when: true

    - name: Store Password
      ansible.builtin.copy:
        content: "{{ generated_password.stdout }}"
        dest: /root/db_pass
        mode: '0600'

    - name: Create Kubernetes Secret
      become: true
      kubernetes.core.k8s:
        namespace: default
        definition:
          api_version: v1
          kind: Secret
          metadata:
            name: rds-creds
          data:
            db_pass: "{{ generated_password.stdout | b64encode }}"

    - name: Create ConfigMap for RDS endpoint
      kubernetes.core.k8s:
        namespace: default
        definition:
          api_version: v1
          kind: ConfigMap
          metadata:
            name: rds-config
          data:
            DB_HOST: " {{ RDS_ENDPOINT }} "

    - name: Seed initial DB
      block:
        - name: Download skeema
          become: true
          ansible.builtin.get_url:
            url: "https://github.com/skeema/skeema/releases/latest/download/skeema_amd64.deb"
            timeout: 120
            dest: /usr/local/skeema.deb
            owner: root
            group: root
            mode: "0755"
        - name: Install skeema
          become: true
          ansible.builtin.apt:
            deb: /usr/local/skeema.deb

        - name: Setup schema
          become: true
          ansible.builtin.command:
            chdir: /root/devops-rampup/infrastructure/db_schemas/movie_db/
            cmd: skeema push -h {{ RDS_ENDPOINT }} -u root -p {{ generated_password.stdout }} -d movie_db
          changed_when: true

        - name: Install deps for seeding DB
          become: true
          block:
            - name: Add nodejs apt key
              ansible.builtin.apt_key:
                url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
                state: present
            - name: Add nodejs PPA
              ansible.builtin.apt_repository:
                repo: deb https://deb.nodesource.com/node_20.x nodistro main
                update_cache: true
            - name: Install nodejs
              ansible.builtin.apt:
                update_cache: true
                name: nodejs
                state: present
            - name: Install NPM dependencies
              community.general.npm:
                path: /root/devops-rampup/movie-analyst-api/

        - name: Seed DB
          become: true
          ansible.builtin.command:
            chdir: /root/devops-rampup/movie-analyst-api/
            cmd: node seeds.js
          changed_when: true
          environment:
            DB_HOST: "{{ RDS_ENDPOINT }}"
            DB_USER: admin
            DB_PASS: "{{ generated_password.stdout }}"
