- name: Install k3s
  hosts: localhost
  roles:
   - role: k8s

- name: Apply kubernetes manifests
  hosts: localhost
  tags: manifests
  tasks:
   - name: Apply kubernetes manifests
     ansible.builtin.command: kubectl apply -k "~/devops-rampup/infrastructure/kubernetes/"
     become: true
     changed_when: true
