- name: "Install some prerequisites"
  become: true
  ansible.builtin.package:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
    state: present

- name: "Add Docker gnupg"
  become: true
  ansible.builtin.apt_key:
    url: 'https://download.docker.com/linux/debian/gpg'
    state: present

- name: "Add Docker repository and update apt cache"
  become: true
  ansible.builtin.apt_repository:
    repo: "deb https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    state: present
    filename: docker
    update_cache: true

- name: "Install Docker"
  become: true
  ansible.builtin.package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: "Enable Docker service"
  become: true
  ansible.builtin.service:
    name: docker
    enabled: true
    state: started
