# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'
VAGRANT_NODE_COUNT = 1
VAGRANT_NODE_DISTR = "debian/bullseye64"

Vagrant.configure("2") do |config|

# MANAGED NODES
  (1..VAGRANT_NODE_COUNT.to_i).each do |i|
    config.vm.define "vm#{i}" do |node|
      node.vm.box = "#{VAGRANT_NODE_DISTR}"
      node.vm.hostname = "vm#{i}.example.com"
      node.vm.network "private_network", ip: "192.0.2.10#{i}"
      node.vm.provision "node", type: "shell", path: "./provision-node.sh", env: {"n" => "#{VAGRANT_NODE_COUNT}"}
      node.vm.provider "libvirt" do |vb|
        vb.memory = 2048
        vb.cpus = 2
      end
    end
  end

end
